# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='source_language',
            field=models.ForeignKey(default=b'en', on_delete=django.db.models.deletion.PROTECT, to='terminator.Language', verbose_name='source language'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='related_concepts',
            field=models.ManyToManyField(blank=True, related_name='_concept_related_concepts_+', to='terminator.Concept', verbose_name='related concepts'),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='subject_fields',
            field=models.ManyToManyField(blank=True, related_name='glossary_subject_fields', to='terminator.Concept', verbose_name='subject fields'),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='subscribers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='subscribers'),
        ),
    ]
