# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminator', '0002_auto_20170915_1152'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='definition',
            unique_together=set([]),
        ),
    ]
