# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminator', '0003_auto_20170921_0742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'get_latest_by': 'id', 'verbose_name': 'definition', 'verbose_name_plural': 'definitions'},
        ),
    ]
