# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:05
from __future__ import unicode_literals

from django.db import migrations, models


def create_concept_reprs(apps, schema_editor):
    Concept = apps.get_model('terminator', 'Concept')
    for c in Concept.objects.all():
        c.update_repr_cache()

class Migration(migrations.Migration):

    dependencies = [
        ('terminator', '0004_definition_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='repr_cache',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
