# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminator', '0007_rename_ConceptLanguageCommentsThread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='language',
            name='grammatical_genders',
            field=models.ManyToManyField(blank=True, to='terminator.GrammaticalGender', verbose_name='grammatical genders'),
        ),
        migrations.AlterField(
            model_name='language',
            name='grammatical_numbers',
            field=models.ManyToManyField(blank=True, to='terminator.GrammaticalNumber', verbose_name='grammatical numbers'),
        ),
    ]
