# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminator', '0010_concept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalresource',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='terminator.Language', verbose_name='language'),
        ),
    ]
