# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
from django.db.models import Max


"""This migration removes all old definitions so that we can reintroduce a
unique index for (concept, language).

It is very slow. It probably doesn't matter.
"""


def remove_definition_history(apps, schema_editor):
    Definition = apps.get_model('terminator', 'Definition')
    qs = Definition.objects.values('concept', 'language').annotate(latest=Max('id'))
    #<QuerySet [{'concept': 1, 'language': u'en', 'latest': 6425},
    #           {'concept': 2, 'language': u'en', 'latest': 16065},
    #           ...]>
    to_delete = []
    for info in qs:
        concept = info['concept']
        language = info['language']
        latest = info['latest']
        to_delete.extend(Definition.objects.filter(
            concept_id=concept,
            language_id=language,
            id__lt=latest,
        ).values_list('id', flat=True))

    if "sqlite" in settings.DATABASES['default']['ENGINE']:
        # SQLite can't handle more than 999 translations (by default). We do it
        # in batches so that testing with SQLite is still possible.
        for i in range(0, len(to_delete), 999):
            Definition.objects.filter(id__in=to_delete[i:i+999]).delete()
    else:
        Definition.objects.filter(id__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('terminator', '0011_resource_lang_optional'),
    ]

    operations = [
             migrations.RunPython(remove_definition_history),
    ]
