# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminator', '0012_remove_definition_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'verbose_name': 'definition', 'verbose_name_plural': 'definitions'},
        ),
        migrations.AlterUniqueTogether(
            name='definition',
            unique_together=set([('concept', 'language')]),
        ),
    ]
