# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 08:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terminator', '0013_definition_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='definition',
            old_name='definition_text',
            new_name='text',
        ),
    ]
