# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminator', '0014_rename_definition_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='process_status',
            new_name='is_finalized',
        ),
    ]
