# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminator', '0015_rename_process_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrativestatus',
            old_name='allows_administrative_status_reason',
            new_name='allows_reason',
        ),
    ]
