# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminator', '0017_definition_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptinlanguage',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='conceptinlanguage',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='is finalized'),
        ),
        migrations.AddField(
            model_name='conceptinlanguage',
            name='summary',
            field=models.TextField(blank=True, verbose_name='summary message'),
        ),
    ]
