# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 06:21
from __future__ import unicode_literals

from django.db import migrations

def move_summary_data(apps, schema_editor):
    SummaryMessage = apps.get_model('terminator', 'SummaryMessage')
    ConceptInLanguage = apps.get_model('terminator', 'ConceptInLanguage')
    for summary in SummaryMessage.objects.all():
        ConceptInLanguage.objects.filter(
                concept_id=summary.concept_id,
                language_id=summary.language_id,
        ).update(
                date=summary.date,
                is_finalized=summary.is_finalized,
                summary=summary.text,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('terminator', '0018_move_summary_fields_to_conceptinlanguage'),
    ]

    operations = [
            migrations.RunPython(move_summary_data)
    ]
