# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 09:02
from __future__ import unicode_literals

from django.db import migrations


def populate_glossary_other_languages(apps, schema_editor):
    Glossary = apps.get_model('terminator', 'Glossary')
    Language = apps.get_model('terminator', 'Language')
    Translation = apps.get_model('terminator', 'Translation')
    Definition = apps.get_model('terminator', 'Definition')
    ExternalResource = apps.get_model('terminator', 'ExternalResource')
    for glossary in Glossary.objects.all():
        languages = set()
        for model in (Translation, Definition, ExternalResource):
            languages.update(set(model.objects.filter(
                concept__glossary=glossary).values_list('language', flat=True)))
        if glossary.source_language_id in languages:
            languages.remove(glossary.source_language_id)
        glossary.other_languages.set(Language.objects.filter(iso_code__in=languages))


class Migration(migrations.Migration):

    dependencies = [
        ('terminator', '0021_glossary_languages'),
    ]

    operations = [
            migrations.RunPython(populate_glossary_other_languages)
    ]
